### PR TITLE
fix: Amber Acorn not hiding score when hide score option is selected

### PR DESCRIPTION
**Pull request by CUexter**
My goal here is to solve #24. 

The logic is simple, if the boss is amber acorn and the number of joker is not zero, then hide the scores

### CODE REVIEW

**Comment by CUexter** [comment]
I haven't test the fix, how do i test it without playing the game from scratch ?

**Comment by CUexter** [comment]
I have tested the fix, and it worked, however i found a more pressing bug when testing #26

**Comment by DivvyCr** [comment]
Appreciate the PR, but I believe a more robust approach would be something like this:

```lua
for _, joker in ipairs(G.jokers.cards) do
   if joker.facing == "back" then return nil end
end
```

Could you test if it works and update the PR?

**Comment by CUexter** [comment]
it works, however the ??? is shown even when no cards are selected, do you want this behavior ? or if you want an extra check ?

**Comment by CUexter** [comment]
Ok i added the feature to only show ??? when cards are selected, also i implemented fixes for #26

**Comment by DivvyCr** [comment]
LGTM. I'll merge after testing for myself, hopefully today/tomorrow.

**Pull request merged**
