### PR TITLE
Fixing 3 Bugs raised in the Discord Thread

### PR DESCRIPTION
**Pull request by CUexter**
1. Fixing the score calculation of The Arm Blind
2. Fixing Midas Mask and Vampire score calculation when using bonus cards, bonus chip of enhancement shouldn't add up together when it is turned from bonus card to gold card/bonus card
3. Fixing Erosion causing negative mult, by capping the add mult, x mult and add chips to non negative/less than x1.

### CODE REVIEW

**Comment by DivvyCr** [comment]
What's the bug fixed by the changes to add_chips/add_mult/x_mult functions? on lines 1475/1479/1483?

**Comment by CUexter** [comment]
It is for the erosion causing negative mult, i think the game doesn't allow joker giving negative chips, minus mult or make the multiplier smaller than 1, so i added those to avoid similar problem such as erosion causing negative mult

**Comment by DivvyCr** [comment]
Implemented in 51488e6cced3d5078a0f794e011869a9fd26bc03 and 784d02d8dcd756679ed31b37a24b5747eb9a8498

**Comment by CUexter** [comment]
how about the vampire and Midas situation

**Pull request closed without merging**
